// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
@type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure:
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually:
  
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      items: [
        'getting-started/setup',
        'getting-started/try-demo-prototype',
      ],
    },
    {
      type: 'category',
      label: 'Building prototypes',
      items: [
        'prototypes/index',
        'prototypes/create-prototype',
        'prototypes/run-prototype-locally',
        'prototypes/create-prototype-pages',
        'prototypes/edit-prototype-pages',
        'prototypes/link-pages',
        'prototypes/nunjucks',
        `prototypes/handling-user-input`,
      ],
    },
    {
      type: 'category',
      label: 'Setting up with variants',
      items: [
        'variants/index',
        'variants/use-a-variant',
        {
          type: 'category',
          label: 'Creating variants',
          items: [
          'variants/creating-variants/understand-variants',
          'variants/creating-variants/create-a-variant',
          'variants/creating-variants/test-a-variant',
          'variants/creating-variants/publish-a-variant',
      ],
    },
      ],
    },
    {
      type: 'category',
      label: 'Configuring with plugins',
      items: [
        'plugins/index',
        'plugins/understand-plugins',
        'plugins/add-plugin',
        'plugins/create-plugin',
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Sharing prototypes',
    //   items: [
    //     'sharing/sharing-prototypes',
    //   ],
    // },
  ],
  
};

export default sidebars;
